variable "client_id" {
  type      = string
  sensitive = true
  default   = ""
}

variable "client_secret" {
  type      = string
  sensitive = true
  default   = ""  
}

variable "subscription_id" {
  type      = string
  sensitive = true
  default   = ""  
}

variable "tenant_id" {
  type      = string
  sensitive = true
  default   = ""  
}

source "azure-arm" "autogenerated_1" {
  client_id                         = var.client_id
  client_secret                     = var.client_secret
  subscription_id                   = var.subscription_id
  tenant_id                         = var.tenant_id
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  location                          = "East US"
  managed_image_name                = "my-custom-image"
  managed_image_resource_group_name = "managed-image-rg"
  os_type                           = "Linux"
  vm_size                           = "Standard_DS2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "sudo apt update && sudo apt upgrade -y",
      "sudo apt install ansible -y"
    ]
  }

  provisioner "ansible-local" {
    playbook_file = "./playbook.yml"
  }
}