source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  client_id                         = "{{APP_ID}}"
  client_secret                     = "{{PASSWORD}}"
  subscription_id                   = "{{SUBSCRIPTION_ID}}"
  tenant_id                         = "{{TENANT_ID}}" 
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  location                          = "East US"
  managed_image_name                = "my-custom-image"
  managed_image_resource_group_name = "managed-image-rg"
  os_type                           = "Linux"
  vm_size                           = "Standard_DS2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "sudo apt update && sudo apt upgrade -y",
      "sudo apt install ansible -y"
    ]
  }

  provisioner "ansible-local" {
    playbook_file = "./playbook.yml"
  }
}