variable "client_id" {
  type      = string
  sensitive = true
}

variable "client_secret" {
  type      = string
  sensitive = true
}

variable "subscription_id" {
  type      = string
  sensitive = true
}

variable "tenant_id" {
  type      = string
  sensitive = true
}
source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
    ExcludeMdeAutoProvisioning = "true"
  }
  build_resource_group_name         = "urjasonipackertest"
  client_id                         = var.client_id
  client_secret                     = var.client_secret
  communicator                      = "winrm"
  image_offer                       = "WindowsServer"
  image_publisher                   = "MicrosoftWindowsServer"
  image_sku                         = "2022-Datacenter"
  managed_image_name                = "windows20222Image"
  managed_image_resource_group_name = "urjasonipackertest"
  os_type                           = "Windows"
  subscription_id                   = var.subscription_id
  tenant_id                         = var.tenant_id
  vm_size                           = "Standard_DS1_v2"
  winrm_insecure                    = true
  winrm_timeout                     = "5m"
  winrm_use_ssl                     = true
  winrm_username                    = "packer"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]
  provisioner "file" {
    source      = "./ConfigureRemotingForAnsible.ps1"
    destination = "/temp/ConfigureRemotingForAnsible.ps1"
  }
  provisioner "powershell" {
    inline = ["/temp/ConfigureRemotingForAnsible.ps1 -forcenewsslcert"]
  }
  provisioner "ansible" {
    playbook_file   = "./playbook-windows.yml"
    user            = "packer"
    use_proxy       = false
    extra_arguments = ["-vvvv", "-e", "ansible_winrm_server_cert_validation=ignore ansible_user=packer"]
  }


  provisioner "powershell" {
    inline = ["while ((Get-Service RdAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
      "while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
      "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
      "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { Write-Output $imageState.ImageState; break } }"
    ]
  }

}
