name: Clean Up Resource Group

on: delete
jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"

        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Checkout
          uses: actions/checkout@v3

        - name: Azure CLI script
          uses: azure/CLI@v1
          with:
            azcliversion: 2.44.1
            inlineScript: |
              az group delete -n ${{ github.event.ref }}          